# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
